[package]
name = "epc"
version = "0.1.0"
authors = ["Russ Garrett <russ@garrett.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "*"
nom = "5"
